#!/usr/bin/env python
# (c) 2017, Alice Ferrazzi <alice.ferrazzi@gmail.com>
#
# This file is part of elivepatch
#
# elivepatch is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# elivepatch is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with elivepatch.  If not, see <http://www.gnu.org/licenses/>.

"""elivepatch API using Flask-RESTful extension."""

from flask import Flask, jsonify, abort, make_response
from flask_restful  import Api, Resource, reqparse, fields, marshal
from elivepatch_server.resources import AgentInfo, dispatcher


def create_app():

    app = Flask(__name__, static_url_path="")
    api = Api(app)

    api.add_resource(AgentInfo.AgentAPI, '/elivepatch/api/', endpoint='root')
    api.add_resource(AgentInfo.AgentAPI, '/elivepatch/api/v1.0/agent', endpoint='agent')
    api.add_resource(dispatcher.getLivePatch, '/elivepatch/api/v1.0/livepatch',
                     endpoint='livepatch')
    api.add_resource(dispatcher.getConfig, '/elivepatch/api/v1.0/config',
                     endpoint='config')
    api.add_resource(dispatcher.getPatch, '/elivepatch/api/v1.0/patch',
                     endpoint='patch')
    return app

if __name__ == '__main__':
    app = create_app()
    app.run(debug=True, host='0.0.0.0')
